### ISSUE TITLE
need example in the readme

### ISSUE THREAD

**Issue by jdar** [willcannings/Ruby-SVD#2]
Hi Will,

Could you provide one simple example of LSA or SVDMatrix in use? I love the approach, but I am having problems using your library.

Darius

**Comment by willcannings** [comment]
Hi Darius,

thanks for the interest! Yep, documentation has been a bit lacking. I wrote this for a startup project I was working on and never got around to documenting it or making sure it was useful for anything but what we were working on. I've updated the gem (to 0.5.1) to fix a few issues under 1.9.2, and to also include an example of how to use the gem (both the SVDMatrix class and the LSA class). Let me know if you want any more info or find any bugs!

**Comment by jdar** [comment]
Will,

Thank you so much for your quick resolution. It works great on some machines now (apparently SVD can be finicky). I'm happy to have your solution running.

I'll be mentioning your gem in a local DCRUG talk in a few weeks. 

Thanks,
Darius
